[package]
name = "Command_ping"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
surge-ping = "0.8.4"
tokio = { version = "1.35", features = ["full"] }
colored = "2.1.0"
anyhow = "1.0"